services:
  - type: web
    name: omegle-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    plan: free
    autoDeploy: true
